stages:
  - build
  - test
  - deploy


.setup-generic: &setup-generic |
  git config --global --add safe.directory '*'
  export CONAN_USER_HOME=$(pwd)/.tmp/
  pip install --upgrade conan_package_tools
  pip install regex
  conan profile new ci --detect --force
  conan profile update settings.compiler.cppstd=20 ci
  echo -e "\n[build_requires]\n&: cmake/3.25.1" >> .tmp/.conan/profiles/ci
  conan remote add --force gitlab https://gitlab.com/api/v4/packages/conan
  conan user -c
  conan user ci_user -r gitlab -p ${CI_JOB_TOKEN}


.setup-clang: &setup-clang
  cache:
    key: clang
    paths:
      - .tmp/
  variables:
    CONAN_NAME: "labrat-robot"
    CONAN_USER: "labrat.eu+robot"
    CONAN_CHANNEL: "clang"
  before_script:
    - *setup-generic
    - conan profile update settings.compiler.libcxx=libc++ ci

.setup-gcc: &setup-gcc
  cache:
    key: gcc
    paths:
      - .tmp/
  variables:
    CONAN_NAME: "labrat-robot"
    CONAN_USER: "labrat.eu+robot"
    CONAN_CHANNEL: "gcc"
  before_script:
    - *setup-generic
    - conan profile update settings.compiler.libcxx=libstdc++11 ci


.build-generic: &build-generic |
  conan create . $CONAN_USER/$CONAN_CHANNEL --build=missing -pr:h=ci

.test-generic: &test-generic |
  conan test --build=missing -pr:h=ci testing $(conan info . | grep -oE "$CONAN_NAME/v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(\+[a-Z0-9\-]+)" | head -n1)@$CONAN_USER/$CONAN_CHANNEL

.deploy-generic: &deploy-generic |
  conan upload $(conan info . | grep -oE "$CONAN_NAME/v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(\+[a-Z0-9\-]+)" | head -n1)@$CONAN_USER/$CONAN_CHANNEL --all -r gitlab


build:clang-14:
  stage: build
  image: conanio/clang14-ubuntu18.04
  <<: *setup-clang
  script:
    - *build-generic

test:clang-14:
  stage: test
  needs: ["build:clang-14"]
  image: conanio/clang14-ubuntu18.04
  <<: *setup-clang
  script:
    - *test-generic

deploy:clang-14:
  stage: deploy
  needs: ["test:clang-14"]
  image: conanio/clang14-ubuntu18.04
  <<: *setup-clang
  script:
    - *deploy-generic


build:gcc-12:
  stage: build
  image: conanio/gcc12-ubuntu18.04
  <<: *setup-gcc
  script:
    - *build-generic

test:gcc-12:
  stage: test
  needs: ["build:gcc-12"]
  image: conanio/gcc12-ubuntu18.04
  <<: *setup-gcc
  script:
    - *test-generic

deploy:gcc-12:
  stage: deploy
  needs: ["test:gcc-12"]
  image: conanio/gcc12-ubuntu18.04
  <<: *setup-gcc
  script:
    - *deploy-generic
