stages:
  - build

variables:
  CONAN_USERNAME: "None"
  CONAN_REFERENCE: "test/v1"
  CONAN_CHANNEL: "None"
  CONAN_LOGIN_USERNAME: "None"
    
.build-template: &build-template
  stage: build
  cache:
    paths:
      - .tmp/
  before_script:
    - export CONAN_USER_HOME=$(pwd)/.tmp/
    - pip install --upgrade conan_package_tools
    - conan user
    - conan profile new ci --detect --force
    - conan profile update settings.compiler.libcxx=libc++ ci
    - pip install regex
    - git config --global --add safe.directory '*'
  script:
    - conan create . labrat.eu+robot/ci --build=missing -pr:b=ci -pr:h=ci
    #- conan remote add gitlab https://gitlab.com/api/v4/packages/conan
    #- conan user ci_user -r gitlab -p ${CI_JOB_TOKEN}
    #- conan upload labrat-robot/v0.0.0+49c9aef@labrat.eu+robot/ci --all -r gitlab

build-clang-14:
  image: conanio/clang14-ubuntu18.04
  <<: *build-template

