stages:
  - setup
  - build
  - test
  - deploy


variables:
  CONAN_NAME: "lbot"
  CONAN_USER: "labrat-eu+lbot"
  CONAN_CHANNEL: "alpha"


.init-docker: &init-docker |
  docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY


.init-generic: &init-generic |
  git config --global --add safe.directory '*'
  git fetch --depth=99999
  export CONAN_HOME=$(pwd)/.tmp/
  mkdir -p .tmp/profiles/
  cp /opt/conan_profile .tmp/profiles/ci
# conan remote add --force gitlab https://gitlab.com/api/v4/packages/conan
# conan remote login gitlab ci_user -p ${CI_JOB_TOKEN}


.init-clang: &init-clang
  cache:
    key: clang
    paths:
      - .tmp/
  before_script:
    - *init-generic

.init-gcc: &init-gcc
  cache:
    key: gcc
    paths:
      - .tmp/
  before_script:
    - *init-generic


.build-generic: &build-generic |
  if [ $LBOT_NIGHTLY_PIPELINE ]; then rm -rf $CONAN_USER_HOME/.conan/data; fi
  conan remove -c $CONAN_NAME/*
  conan create . --name $CONAN_NAME --user $CONAN_USER --channel $CONAN_CHANNEL -b=missing -pr:h=ci -pr:b=ci

.test-generic: &test-generic |
  CTEST_OUTPUT_ON_FAILURE=1 conan test -b=missing -pr:h=ci -pr:b=ci testing $CONAN_NAME/$(conan inspect . | grep -Po "(?<=version: ).*" | head -n1)@$CONAN_USER/$CONAN_CHANNEL
  cp `find -L testing/build/ -name report.xml` test_report.xml

.deploy-generic: &deploy-generic |
  conan upload $CONAN_NAME/$(conan inspect . | grep -Po "(?<=version: ).*" | head -n1)@$CONAN_USER/$CONAN_CHANNEL --all -r gitlab --retry 5 --retry-wait 10


setup:clang-17:
  stage: setup
  rules:
    - changes:
      - .ci/clang-17/*
    - if: $LBOT_NIGHTLY_PIPELINE
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - *init-docker
  script:
    - cd .ci/clang-17
    - docker build -t $CI_REGISTRY_IMAGE:clang-17 .
    - docker push $CI_REGISTRY_IMAGE:clang-17

setup:gcc-13:
  stage: setup
  rules:
    - changes:
      - .ci/gcc-13/*
    - if: $LBOT_NIGHTLY_PIPELINE
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - *init-docker
  script:
    - cd .ci/gcc-13
    - docker build -t $CI_REGISTRY_IMAGE:gcc-13 .
    - docker push $CI_REGISTRY_IMAGE:gcc-13

setup:doxygen:
  stage: setup
  rules:
    - changes:
      - .ci/doxygen/*
    - if: $LBOT_NIGHTLY_PIPELINE
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - *init-docker
  script:
    - cd .ci/doxygen
    - docker build -t $CI_REGISTRY_IMAGE:doxygen .
    - docker push $CI_REGISTRY_IMAGE:doxygen


build:clang-17:
  stage: build
  image: $CI_REGISTRY_IMAGE:clang-17
  <<: *init-clang
  script:
    - *build-generic

test:clang-17:
  stage: test
  needs: ["build:clang-17"]
  image: $CI_REGISTRY_IMAGE:clang-17
  artifacts:
    when: always
    paths:
      - test_report.xml
    reports:
      junit: test_report.xml
  <<: *init-clang
  script:
    - *test-generic

# Hidden until GitLab supports conan 2.0
.deploy:clang-17:
  stage: deploy
  rules:
    - if: $CI_COMMIT_REF_PROTECTED
    - if: $CI_COMMIT_TAG
  image: $CI_REGISTRY_IMAGE:clang-17
  <<: *init-clang
  script:
    - *deploy-generic


build:gcc-13:
  stage: build
  image: $CI_REGISTRY_IMAGE:gcc-13
  <<: *init-gcc
  script:
    - *build-generic

test:gcc-13:
  stage: test
  needs: ["build:gcc-13"]
  image: $CI_REGISTRY_IMAGE:gcc-13
  artifacts:
    when: always
    paths:
      - test_report.xml
    reports:
      junit: test_report.xml
  <<: *init-gcc
  script:
    - *test-generic

# Hidden until GitLab supports conan 2.0
.deploy:gcc-13:
  stage: deploy
  rules:
    - if: $CI_COMMIT_REF_PROTECTED
    - if: $CI_COMMIT_TAG
  image: $CI_REGISTRY_IMAGE:gcc-13
  <<: *init-gcc
  script:
    - *deploy-generic

pages:
  stage: deploy
  image: $CI_REGISTRY_IMAGE:doxygen
  <<: *init-gcc
  script:
    - conan source .
    - conan build . -pr:h=ci -pr:b=ci -o dry_run=True
    - cd build/Release
    - cmake . -DLBOT_ENABLE_DOCS=ON
    - make generate-docs
    - cd ../../
    - cp -r docs/html public
  artifacts:
    paths:
      - public
